# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc738f32abe8fab7b8145a17437ae677b2fd610991c794f3ad1015d8b775e9afb525ca44ed5c59c9e290eb4537850c99ca40933c8f7536132b8d1b81935b20f4

test:
  secret_key_base: e093e4182457cc95758089f480c734ce02bc9f34955c4ee2364d75f17ceb32b5b6d504b4b4b276551a6c360efb479ec3f00dd9d4fc8db89c8d85d6de563ccb71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
